### PR TITLE
Feature Request by crashzk

### PR DESCRIPTION
**Pull request by crashzk**
- Update Translations;
- Update README;
- Changed message colors;
- Changed names of the `.ini` config files;
- Moved configs `.ini` per folder **playerskin**;

### CODE REVIEW

**Comment by crashzk** [comment]
I tested these modifications on my servers these days, all right, working perfectly.

**Comment by crashzk** [comment]
I will be carrying out tests with this new version, everything will be right for you, so you can check and see if it can be accepted on the original fork.

**Comment by crashzk** [comment]
I finalized the changes, the modifications made are:
- Update Translations;
- Update README;
- Changed message colors;
- Changed names of the `.ini` config files;
- Moved configs `.ini` per folder **playerskin**;

I tested the changes on my servers, in all the plugin worked correctly.

I moved the files to the **playerskin** folder to keep something organized, and to do the test if everything was right, I changed the file names just in case.

So far without errors on my server, I can choose skins normally.

@safra36 is now waiting for your verification to see if there is no error, being all right and according to your rules for PR just merge with the main project.

**Comment by crashzk** [comment]
After a few hours of testing, the plugin is still ok, players can choose skins, all right apparently.

However, checking the server's error log, it shows the following error:
```
L 04/15/2020 - 18:05:10: [SM] Exception reported: Invalid key value handle 13c91e18 (error 3)
L 04/15/2020 - 18:05:10: [SM] Blaming: PlayerSkin.smx
L 04/15/2020 - 18:05:10: [SM] Call stack trace:
L 04/15/2020 - 18:05:10: [SM]   [0] KvGetString
L 04/15/2020 - 18:05:10: [SM]   [1] Line 583, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons\sourcemod\scripting\PlayerSkin.sp::SkinMenuHandle
L 04/15/2020 - 18:15:49: [SM] Exception reported: Invalid key value handle 79921da8 (error 3)
L 04/15/2020 - 18:15:49: [SM] Blaming: PlayerSkin.smx
L 04/15/2020 - 18:15:49: [SM] Call stack trace:
L 04/15/2020 - 18:15:49: [SM]   [0] KvGetString
L 04/15/2020 - 18:15:49: [SM]   [1] Line 583, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons\sourcemod\scripting\PlayerSkin.sp::SkinMenuHandle
```
I don't know if it would have to do with the error listed here before: #5

**Comment by safra36** [comment]
I just saw what you're doing here i was busy with adding modification to another game so i missed out your request, i'll check your last version for errors and let you know what could cause the error if i came to something, thanks for the contribution

**Comment by crashzk** [comment]
Oops, any news? Did you get one checked?

**Comment by safra36** [comment]
didn't check it much but as i remember the exceptions are not too important they are mostly because the menu handle is already closed when the CloseHandle function gets called, there were some issue tbh like some file name changes made the skin categories feature not to work tested it about 8 days ago not sure if i missed anything, but overall most of the things were working great, i'll try to finish my review as fast as i can and merg it to the master branch
Thanks!

**Pull request closed without merging**
